apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: Minimal Python
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.jcollier-rhoaijul1521.devcluster.openshift.com/projects/rhtap-app?notebookLogout=test-jul15-5test
    opendatahub.io/accelerator-name: ''
    openshift.io/description: ''
    openshift.io/display-name: test-jul15-5test
    notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:2024.1'
    notebooks.opendatahub.io/last-size-selection: Small
  name: test-jul15-5test
  namespace: rhtap-app
  labels:
    app: test-jul15-5test
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
spec:
  template:
    spec:
      affinity: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 8Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhtap-app/test-jul15-5test/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: test-jul15-5test
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhtap-app/test-jul15-5test/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/rhtap-app/test-jul15-5test
                                  --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1'
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: test-jul15-5test
            - mountPath: /dev/shm
              name: shm
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1'
          workingDir: /opt/app-root/src
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
        - name: test-jul15-5test
          persistentVolumeClaim:
            claimName: test-jul15-5test-rhoai
        - emptyDir:
            medium: Memory
          name: shm